// Generated by CoffeeScript 1.4.0
(function() {
  var EventEmitter, WebSocket, parseMessage, request, rtm, sendInitialPresenceEvent, slackData, userIdToNick;

  request = require('request');

  WebSocket = require('ws');

  EventEmitter = require('events').EventEmitter;

  rtm = new EventEmitter;

  slackData = {};

  parseMessage = function(msg) {
    msg = JSON.parse(msg);
    if (msg.type === 'presence_change') {
      if (msg.user === 'USLACKBOT') {
        return;
      }
      rtm.emit(msg.presence, userIdToNick(msg.user));
    } else if (msg.type === 'hello') {
      rtm.emit('ready');
    } else {
      rtm.emit(msg.type, msg);
    }
    rtm.emit('*', msg);
  };

  userIdToNick = function(userid) {
    var user, users, _i, _len;
    users = slackData.users;
    for (_i = 0, _len = users.length; _i < _len; _i++) {
      user = users[_i];
      if (user.id === userid) {
        return user.name;
      }
    }
    return 'unknown';
  };

  sendInitialPresenceEvent = function(users) {
    var user, _i, _len;
    for (_i = 0, _len = users.length; _i < _len; _i++) {
      user = users[_i];
      if (user.id !== 'USLACKBOT') {
        rtm.emit(user.presence, user.name);
      }
    }
  };

  module.exports = function(API_TOKEN) {
    request.get({
      url: 'https://slack.com/api/rtm.start?token=' + API_TOKEN,
      json: true
    }, function(err, res, json) {
      var ws;
      if (err) {
        throw err;
      }
      slackData = json;
      sendInitialPresenceEvent(slackData.users);
      ws = new WebSocket(json.url);
      ws.on('message', parseMessage);
      ws.on('open', function(socket) {
        return rtm.emit('connect');
      });
      ws.on('error', function(err) {
        return rtm.emit('error', err);
      });
    });
    return rtm;
  };

}).call(this);
